### ISSUE TITLE
minor issue in search page

### ISSUE THREAD

**Issue by juampavilla** [juampavilla/SistemaDeControl-ColegioDeOdontologos#16]
![screenshot from 2017-10-01 10-57-54](https://user-images.githubusercontent.com/22420441/31055325-8f1ea224-a697-11e7-9acb-2e572794f9c1.png)

**Comment by fvitale** [comment]
Yo lo veo bien Villa, me decis si lo seguis viendo mal ahi?
<img width="1338" alt="capture 2017-11-11 a la s 11 10 38" src="https://user-images.githubusercontent.com/6042851/32690183-1cb54922-c6d1-11e7-92d9-66a1fab101e6.png">

**Comment by fvitale** [comment]
si ya se arreglo con los ajustes que hemos hecho marcale Close al issue

**Comment by fvitale** [comment]
arreglado en https://github.com/juampavilla/SistemaDeControl-ColegioDeOdontologos/pull/21

**Comment by juampavilla** [comment]
joya fer!,

pero no lo puedo probar
unknown attribute 'cp' for Profesional.
/home/juampa/.rvm/gems/ruby-2.4.2@SACO/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:48:in
`_assign_attribute'

puede ser que cambiaste los csv originales??


abrazo, veo si mañana me pego una vuelta por tu casa

hablamos

2017-11-11 11:11 GMT-03:00 Fernando Vitale <notifications@github.com>:
